version: "3.9"

services:
  backend:
    image: shn27/reflex-backend:latest
    container_name: reflex-backend
    ports:
      - "8080:8080"
    env_file:
      - .env.example
    restart: unless-stopped

  frontend:
    image: shn27/reflex-frontend:latest
    container_name: reflex-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=ws://backend:8080/ws
    depends_on:
      - backend
    restart: unless-stopped